### ISSUE TITLE
gravity.es fails for unconstrained model due to missing tTable

### ISSUE THREAD

**Issue by yoavram** [jeffreyevans/GeNetIt#2]
When I apply `gravity.es` to a constrained model it works well, but when I apply it to an unconstrained model I get "Error in sqrt(eff$df) : non-numeric argument to mathematical function". 
I looked at the code (https://github.com/jeffreyevans/GeNetIt/blob/master/R/gravity.es.R) and it seems that the unconstrained model summary does not have a `tTable` attribute, and that causes the bug.

```R
> null <- GeNetIt::gravity(y = y, d = "distance", group = "Site1", data = data, ln = FALSE, constrained = FALSE)
> gravity.es(null)
> Error in sqrt(eff$df) : non-numeric argument to mathematical function
> summary(null$gravity)$tTable
NULL
```

Any suggestions?

**Comment by yoavram** [comment]
And a possible working solution, with new/changed code marked with `# YR`:
```R
gravity.es.lm <- function(x, actual.n = FALSE, alpha = 0.95) {
  if(!inherits(x, "gravity")) 
    stop(x, " is not a valid gravity model object")	
  df <- x$gravity$df.residual # YR
  t <- coef(summary(x$gravity))[, "t value"] # YR
  p <- coef(summary(x$gravity))[, "Pr(>|t|)"] # YR
  eff <- data.frame(t.value = t, df = df) # YR using t, df here instead of getting it from $tTable
  eff$cohen.d <- (2 * eff$t.value) / sqrt(eff$df)
  eff <- eff[-1,]
  eff <- data.frame(eff, p.value=round(p, 6)[-1]) # YR using p here instead of getting it from $tTable
  cohen.ci <- function(d, n, conf.level = alpha) {
    deg.f = n + n - 2
    #SD <- sqrt(((n + n)/(n * n) + 0.5 * es[,1][i] ^ 2 / deg.f) * 
    #          ((n + n) / deg.f))
    SD <- sqrt(((n + n)/(n * n) + 0.5 * d ^ 2 / deg.f) * 
                 ((n + n) / deg.f))				
    Z <- -stats::qt((1 - alpha) / 2, deg.f)
    conf.int <- c(d - Z * SD, d + Z * SD)
    ci <- c(low.ci=conf.int[1], up.ci=conf.int[2])
    return(ci)
  }	
  ci <- list()	
  for(i in 1:nrow(eff)) {
    if(actual.n) N = length(x$y) else N = eff[,2][i] 
    ci[[i]] <- cohen.ci(d = eff[,3][i], n = N)
  }
  ci <- as.data.frame(do.call("rbind", ci))
  return(data.frame(eff, ci))
}
```

**Comment by jeffreyevans** [comment]
Yoav,
Sorry about the delay. I have pushed a new development version of tGeNetIt to GitHub. There is a fix for this issue along with some minor bug fixes and enhancements to the gravity function and a complete reworking of the predict method. I acknowledge you in the NEWS file. If you verify your specifics; full name (family and given) and, email, I will add you as a package contributor.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physiology
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>

From: Yoav Ram ***@***.***>
Sent: Wednesday, July 28, 2021 12:10 AM
To: jeffreyevans/GeNetIt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/GeNetIt] gravity.es fails for unconstrained model due to missing tTable (#2)


When I apply gravity.es to a constrained model it works well, but when I apply it to an unconstrained model I get "Error in sqrt(eff$df) : non-numeric argument to mathematical function".
I looked at the code (https://github.com/jeffreyevans/GeNetIt/blob/master/R/gravity.es.R<https://github.com/jeffreyevans/GeNetIt/blob/master/R/gravity.es.R>) and it seems that the unconstrained model summary does not have Y

> null <- GeNetIt::gravity(y = y, d = "distance", group = "Site1", data = data, ln = FALSE, constrained = FALSE)

> gravity.es(null)

> Error in sqrt(eff$df) : non-numeric argument to mathematical function

> summary(null$gravity)$tTable

NULL

Any suggestions?

**Comment by yoavram** [comment]
How do I install the dev version directly from GitHub? Just call `remotes::install_github("jeffreyevans/GeNetIt")`?

It's Yoav Ram <yoav@yoavram.com>

Another related question - `gravity.es` uses Cohen's D, but in Murphy et al 2010, which is cited in the source code comments, they use McFadden's rho^2. Why the difference?

**Comment by jeffreyevans** [comment]
Yes, you use “remotes::install_github” to install development package versions from GitHub repositories. Murphy et al., (2010) used the McFadden rho^2 as a corrected R^2 and not as an effect size. Honesty, effect sizes in mixed effects models are very questionable. Additionally, in gravity models the entire equation is log transformed so, effect sizes would not be on any of the parameters scale(s) and everything would have to be back-transformed. If you are wanting to evaluate parameter contribution, I would recommend taking a look at the “emmeans” package, which supports nlme object classes.

When I get around to a major package update, I am planning on incorporating a more robust way of evaluating parameters effects along with several other enhancements that are on my to-do list. I have already made some significant improvements to existing code that are more performance focused that on adding additional features.

Best,
Jeff
