### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [jeffreyevans/GeNetIt#3]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

with apologies - I think the **rgeos** import is redundant, and may safely be replaced by **terra** for recent **raster**.

**Comment by jeffreyevans** [comment]
Thank you, I had forgot to make these updates. They dependencies exist because I was trying to offer support for modern (sf, terra) and legacy (sp, raster) spatial object types. But, I guess they are no longer necessary and it is best to force users to adopting the new classes.

Best,
Jeff

From: Roger Bivand ***@***.***>
Sent: Thursday, December 15, 2022 5:47 AM
To: jeffreyevans/GeNetIt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/GeNetIt] Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools** (Issue #3)


This package depends on (depends, imports or suggests) raster and one or more of the retiring packages rgdal, rgeos or maptools (https://r-spatial.org/r/2022/04/12/evolution.html<https://r-spatial.org/r/2022/04/12/evolution.html>, https://r-spatial.org/r/2022/12/14/evolution2.html<https://r-spatial.org/r/2022/12/14/evolution2.html>). Since raster 3.6.3, all use of external FOSS library functionality has been transferred to terra, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

with apologies - I think the rgeos import is redundant, and may safely be replaced by terra for recent raster.

**Comment by rsbivand** [comment]
Classes in **sp** and **raster** remain, and can be coerced to and from **terra** classes. So if your workflows need backward compatibility, you can keep that by coercion. See https://github.com/rsbivand/sf_asdar2ed and https://rsbivand.github.io/rgrass/articles/coerce.html for coercion examples.

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.
